apiVersion: apps/v1
kind: Deployment
metadata:
  name: constellationdevservice
  labels:
    app: constellationdevservice
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: constellationdevservice
  template:
    metadata:
      labels:
        app: constellationdevservice
    spec:
      containers:
      - name: constellationdevservice
        image: spacexstarlink.azurecr.io/constellationdevrepo:V1.0.0.1
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 250m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: constellationdevservice
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082

        

